package com.aitt.dto;

import com.aitt.entity.User;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class UserDto {
//we nt use id in dto as its autogenerated. Also below variables request will come to us via postman.Add valiation in dto only.
	
	@NotNull(message = "Username shouldn't be null")
	private String name;
	
	@Email(message = "Email not valid")
	private String email;
	
	@NotNull(message = "Please enter valid mobile number")
	private String mobile;
	private String gender;
	
	@Min(18)
	@Max(60)
	private int age;
	
	@NotBlank    //it means not null n not empty both
	private String nationality;
}
