spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testDb
    username: root
    password: root
    driver-class-name: org.h2.Driver
    
  jpa:
    show-sql: true
    
server:
  port: 9090    